Repository kubernetes-sigs/cluster-api-provider-kubemark, pull requests merged in 2022-12, with the labels that each got.

#54 Update K8s and CAPI dependencies
  .github/workflows/test.yaml
  README.md
  controllers/kubemarkmachine_controller.go
  go.mod
  go.sum
  hack/tests/resources/docker-control-plane.yaml
  hack/tests/utils/kind-with-registry.sh
  main.go
  templates/cluster-template-capd.yaml
Labels: approved, lgtm, cncf-cla: yes, size/XL

#60 update dockerfile to use golang 1.19
  Dockerfile
Labels: approved, lgtm, size/XS, cncf-cla: yes

#57 Fixup publish images
  hack/tools/go.mod
  hack/tools/go.sum
  hack/tools/publish-kubemark-images.go
Labels: approved, lgtm, cncf-cla: yes, size/L

#62 update configs for release 0.5.0
  README.md
  clusterctl-settings.json
  metadata.yaml
Labels: approved, lgtm, size/XS, cncf-cla: yes

#64 align main flags
  Makefile
  controllers/kubemarkmachine_controller.go
  controllers/kubemarkmachinetemplate_controller.go
  go.mod
  go.sum
  hack/tools/go.mod
  hack/tools/go.sum
  hack/tools/tools.go
  main.go
  tilt-provider.json
Labels: size/XXL, approved, lgtm, cncf-cla: yes

#65 use contextual logging
  controllers/kubemarkmachine_controller.go
  controllers/kubemarkmachinetemplate_controller.go
  go.mod
  main.go
Labels: approved, lgtm, cncf-cla: yes, size/L

#68 Setup dependabot
  .github/PULL_REQUEST_TEMPLATE.md
  .github/dependabot.yml
Labels: size/M, approved, lgtm, cncf-cla: yes
