Repository kubernetes-sigs/cluster-api-provider-kubemark, pull requests merged in 2022-05, with the labels that each got.

#41 Update test deployment manifest for workload cluster
  hack/tests/resources/kubemark-machine-deployment.yaml
Labels: approved, lgtm, size/XS, cncf-cla: yes

#42 clean up linting errors
  controllers/kubemarkmachine_controller_test.go
  controllers/kubemarkmachinetemplate_controller.go
Labels: approved, lgtm, size/XS, cncf-cla: yes

#43 update e2e test to capi v1.0
  README.md
  hack/tests/Makefile
  hack/tests/resources/cert-manager/v1.1.0/cert-manager.yaml
  hack/tests/resources/cert-manager/v1.5.3/cert-manager.yaml
  metadata.yaml
Labels: size/XXL, approved, lgtm, cncf-cla: yes

#44 update capi manifests to v1beta1
  hack/tests/resources/docker-control-plane.yaml
  hack/tests/resources/kubemark-machine-deployment.yaml
  templates/cluster-template-capd.yaml
  templates/cluster-template.yaml
Labels: size/M, approved, lgtm, cncf-cla: yes

#46 updating files for release 0.3.0
  README.md
  clusterctl-settings.json
  metadata.yaml
Labels: approved, lgtm, size/S, cncf-cla: yes

#48 update the release instructions
  RELEASE.md
Labels: approved, lgtm, size/XS, cncf-cla: yes
